image:
  repository: infisical/infisical-gateway
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

secret:
  # create a new secret (if true) or use existing (if false)
  create: true
  # name of the secret to use/create
  name: "infisical-gateway-secrets"

  # Secret data (only used if create: true)
  data:
    TOKEN: ""
    INFISICAL_API_URL: "https://app.infisical.com"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: true

securityContext:
  runAsNonRoot: true

affinity: {}
tolerations: {}
nodeSelector: {}
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
