apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: infisical-api-secret-sample-push
spec:
  resyncInterval: 1m
  hostAPI: https://app.infisical.com/api

  # Optional, defaults to replacement.
  updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

  # Optional, defaults to no deletion.
  deletionPolicy: Delete # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

  destination:
    projectId: <project-id>
    environmentSlug: <env-slug>
    secretsPath: <secret-path>

  push:
    secret:
      secretName: push-secret-demo # Secret CRD
      secretNamespace: default
      template:
        includeAllSecrets: false
        data:
          # Encodes the data so it's stored as base64 in Infisical.
          API_KEY: "{{ .API_KEY.Value }}"
          DATABASE_URL: "{{ .DATABASE_URL.Value }}"
          ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY.Value }}"
          OTHER_VALUE: "{{ encodeBase64 .API_KEY.Value }} {{ encodeBase64 .DATABASE_URL.Value }} {{ encodeBase64 .ENCRYPTION_KEY.Value }}"

  # Only have one authentication method defined or you are likely to run into authentication issues.
  # Remove all except one authentication method.
  authentication:
    awsIamAuth:
      identityId: <machine-identity-id>
    azureAuth:
      identityId: <machine-identity-id>
    gcpIamAuth:
      identityId: <machine-identity-id>
      serviceAccountKeyFilePath: </path-to-service-account-key-file.json>
    gcpIdTokenAuth:
      identityId: <machine-identity-id>
    kubernetesAuth:
      identityId: <machine-identity-id>
      serviceAccountRef:
        name: <secret-name>
        namespace: <secret-namespace>
    universalAuth:
      credentialsRef:
        secretName: <secret-name> # universal-auth-credentials
        secretNamespace: <secret-namespace> # default
