name: Build Binaries

on:
    push:
        branches:
            - daniel/infisical-binary
    pull_request:
        branches:
            - daniel/infisical-binary

jobs:
    build-linux:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    [
                        "node18-linux-x64",
                        "node18-linux-x86",
                        "node18-linux-armv7",
                        "node18-linux-arm64",
                        "node18-alpine-x64",
                        "node18-alpine-x86",
                        "node18-alpine-armv7",
                        "node18-alpine-arm64",
                        "node18-linuxstatic-x64",
                        "node18-linuxstatic-x86",
                        "node18-linuxstatic-armv7",
                        "node18-linuxstatic-arm64"
                    ]

        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies (backend)
              run: npm install

            - name: Install dependencies (frontend)
              run: npm install --prefix ../frontend

            - name: Prerequisites for pkg
              run: npm run binary:build

            - name: Build binary
              run: npx pkg --no-bytecode --public-packages "*" --targets ${{matrix.target}} .

            - name: Upload binaries
              uses: actions/upload-artifact@v3
              with:
                  name: binaries-${{ matrix.target }}
                  path: ./backend/binary/

    build-macos:
        runs-on: macos-latest
        strategy:
            matrix:
                target: ["node18-macos-x64", "node18-macos-arm64"]

        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies (backend)
              run: npm install

            - name: Install dependencies (frontend)
              run: npm install --prefix ../frontend

            - name: Prerequisites for pkg
              run: npm run binary:build

            - name: Build binary
              run: npx pkg --no-bytecode --public-packages "*" --targets ${{matrix.target}} .

            - name: Upload binaries
              uses: actions/upload-artifact@v3
              with:
                  name: binaries-${{ matrix.target }}
                  path: ./backend/binary/

    build-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                target: ["node18-win-x64", "node18-win-x86"]

        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies (backend)
              run: npm install

            - name: Install dependencies (frontend)
              run: npm install --prefix ../frontend

            - name: Prerequisites for pkg
              run: npm run binary:build

            - name: Build binary
              run: npx pkg --no-bytecode --public-packages "*" --targets ${{matrix.target}} .

            - name: Upload binaries
              uses: actions/upload-artifact@v3
              with:
                  name: binaries-${{ matrix.target }}
                  path: ./backend/binary/
