name: Build Binaries

on:
    push:
        branches:
            - daniel/infisical-binary
    pull_request:
        branches:
            - daniel/infisical-binary

defaults:
    run:
        working-directory: ./backend

jobs:
    build-and-release:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                arch: [x64, arm64]
                os: [linux, macos, win]
                include:
                    - os: linux
                      docker-image: node:18-buster
                    - os: macos
                      docker-image: node:18-buster
                    - os: win
                      docker-image: node:18-buster

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: 🐋 Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build with Docker
              run: |
                  docker run --rm \
                  --platform=${{ matrix.os }} \
                  -v ${{ github.workspace }}/backend:/workspace/backend \
                  -v ${{ github.workspace }}/frontend:/workspace/frontend \
                  -w /workspace/backend \
                  ${{ matrix.docker-image }} \
                  bash -c "npm install -g pkg && npm install && npm install --prefix ../frontend && npm run binary:build && pkg --no-bytecode --public-packages \"*\" --public --target node18-${{ matrix.os }}-${{ matrix.arch }} --output ./binary/infisical-${{ matrix.os }}-${{ matrix.arch }} ."

            - name: List files
              run: ls -la ./binary

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: infisical-${{ matrix.os }}-${{ matrix.arch }}
                  path: backend/binary/infisical-${{ matrix.os }}-${{ matrix.arch }}
