name: Build Binaries

on:
    push:
        branches:
            - daniel/infisical-binary
    pull_request:
        branches:
            - daniel/infisical-binary

defaults:
    run:
        working-directory: ./backend

jobs:
    build-and-release:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                arch:
                    - x64
                    - arm64
                node-version:
                    - 18
                os:
                    - linux
                    - macos
                    - win

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies (backend)
              run: npm install

            - name: Install dependencies (frontend)
              run: npm install --prefix ../frontend

            - name: Prerequisites for pkg
              run: npm run binary:build

            - name: Package into node binary
              run: pkg --no-bytecode --public-packages \"*\" --public --target host --debug .

            # - name: Upload artifact
            # uses: actions/upload-artifact@v3
            # with:
            # name: ${{ steps.pkg.outputs.artifact-key }}
            # path: ${{ steps.pkg.outputs.file }}
