name: Release Gateway Docker Image
on:
    push:
        tags:
            - "infisical-gateway/v*.*.*"

permissions:
    contents: write

jobs:
    release-image:
        name: Release Gateway Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Extract version from tag
              id: extract_version
              run: echo "::set-output name=version::${GITHUB_REF_NAME#infisical-gateway/}"

            - name: Checkout code
              uses: actions/checkout@v4

            - name: 🔧 Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: 🔧 Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: 🐋 Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: |
                      infisical/gateway:latest
                      infisical/gateway:${{ steps.extract_version.outputs.version }}
