name: Go CLI Tests
on: [push] # Test

jobs:
    test:
        defaults:
            run:
                working-directory: ./cli
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21.x"
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -v ./...
            - name: Test with the Go CLI
              run: TEST_MODE=true go test -v -count=1 ./test
