name: Go CLI Tests

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - "cli/**"

jobs:
    call-workflow:
        uses: ./.github/workflows/run-cli-tests.yml
        secrets:
            CLI_TESTS_UA_CLIENT_ID: ${{ secrets.CLI_TESTS_UA_CLIENT_ID }}
            CLI_TESTS_UA_CLIENT_SECRET: ${{ secrets.CLI_TESTS_UA_CLIENT_SECRET }}
            CLI_TESTS_SERVICE_TOKEN: ${{ secrets.CLI_TESTS_SERVICE_TOKEN }}
            CLI_TESTS_PROJECT_ID: ${{ secrets.CLI_TESTS_PROJECT_ID }}
            CLI_TESTS_ENV_SLUG: ${{ secrets.CLI_TESTS_ENV_SLUG }}

    test:
        name: Go CLI Tests
        runs-on: ubuntu-latest
        needs: [call-workflow]
        steps:
            - name: Hello world
              run: echo "Hello world"
